# Generated by Django 6.1 on 2026-08-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='api.equipmenttype')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='api.inspectiontype')),
            ],
            options={
                'db_table': 'checklist_template',
                'ordering': ['section_name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_label', models.CharField(max_length=500)),
                ('section', models.CharField(blank=True, max_length=150, null=True)),
                ('response_type', models.CharField(choices=[('YES_NO', 'Yes / No'), ('OK_NOT_OK', 'OK / Not OK'), ('SATISFACTORY', 'Satisfactory'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('DATE', 'Date'), ('CHOICE', 'Choice')], default='TEXT', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.checklisttemplate')),
            ],
            options={
                'db_table': 'checklist_item',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=50)),
                ('position_name', models.CharField(max_length=150)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.equipment')),
            ],
            options={
                'db_table': 'equipment_position',
                'ordering': ['sequence', 'position_code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('R', 'R Phase'), ('Y', 'Y Phase'), ('B', 'B Phase'), ('A', 'A Phase'), ('B2', 'B Phase'), ('C', 'C Phase')], max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_phases', to='api.equipment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.inspectionreport')),
            ],
            options={
                'db_table': 'inspection_phase',
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_choice', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='api.checklistitem')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='api.equipment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='api.inspectionreport')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.equipmentposition')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.inspectionphase')),
            ],
            options={
                'db_table': 'checklist_response',
                'ordering': ['checklist_item__sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('inspection_type', 'equipment_type', 'section_name', 'version'), name='unique_checklist_template_version'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('template', 'item_code'), name='unique_item_code_per_template'),
        ),
        migrations.AddConstraint(
            model_name='equipmentposition',
            constraint=models.UniqueConstraint(fields=('equipment', 'position_code'), name='unique_position_per_equipment'),
        ),
        migrations.AddConstraint(
            model_name='inspectionphase',
            constraint=models.UniqueConstraint(fields=('report', 'equipment', 'phase'), name='unique_phase_per_report_equipment'),
        ),
    ]
