# Generated by Django 6.1 on 2026-08-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_checklisttemplate_checklistitem_equipmentposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbs',
            name='zone_office',
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('office_type', models.CharField(choices=[('SADAR', 'Sadar Office'), ('ZONAL', 'Zonal Office'), ('SUB_ZONAL', 'Sub-Zonal Office')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='api.pbs')),
            ],
            options={
                'db_table': 'office',
                'ordering': ['office_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('pbs', 'code'), name='unique_office_code_per_pbs')],
            },
        ),
    ]
