# Generated by Django 6.1 on 2026-08-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pbs_zone_office_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('SATISFACTORY', 'Satisfactory'), ('UNSATISFACTORY', 'Unsatisfactory'), ('NOT_TESTED', 'Not Tested')], default='NOT_TESTED', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results', to='api.equipment')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.inspectionphase')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.equipmentposition')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.inspectionreport')),
            ],
            options={
                'db_table': 'test_result',
                'ordering': ['-test_date', '-id'],
            },
        ),
    ]
